#!/bin/sh
# postinst script for ardesia
#
# see: dh_installdeb(1)

set -e

xdg-icon-resource install --mode system --novendor --context mimetypes --size 48 /usr/share/ardesia/ui/icons/application-x-iwb.png
xdg-mime install --mode system /usr/share/ardesia/ui/iwb-mime.xml
xdg-desktop-menu install --mode system --novendor /usr/share/applications/ardesia.desktop
